### ISSUE TITLE
How to reduce processing time

### ISSUE THREAD

**Issue by chuan298** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#10]
Hi, 
I am building the fingerprint verification app but your enhance algorithm takes 2.5s. How can I to reduce processing time? 
Thank you.

**Comment by Utkarsh-Deshmukh** [comment]
@chuan298 Here are a few ways to speed up the process:
- converting the algorithm from python to cpp
- using hardware accelerators and simd instructions
- increasing the value of the variable "angleInc" (you can very easily do this if you are using the distribution from pip. if not, then you can change this variable in the class "FingerprintImageEnhancer"). Note that by increasing this value, you will make the enhancement more coarse
- downsampling your input image (be careful with this approach)
- increasing the value of the variable "ridge_segment_blksze". Note that by increasing this value, you will be making your enhancement more coarse

Hope this was helpful

**Comment by chuan298** [comment]
Thank you very much!
