### ISSUE TITLE
Hi  Utkarsh, would you please tell why  this line need to times 6 ?  thanks 

### ISSUE THREAD

**Issue by zhenkesiluo** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#12]
in  ridge_orient.py : 

rows,cols = im.shape;
sze = np.fix(6*gradientsigma);   # this line 
if np.remainder(sze,2) == 0:
      sze = sze+1;

**Comment by Utkarsh-Deshmukh** [comment]
Its a redundant parameter. The way it operates is that before computing image gradients, it smoothens the image (thus getting gradient of a gaussian). The multiplication by 6 is done such that we have a sufficiently large kernel size for gaussian smoothing (such that all the possible sigma values can get implemented without running out of kernel size)
