### ISSUE TITLE
Ridge extraction for fingerprint patches

### ISSUE THREAD

**Issue by gowrijsuria** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#13]
Hi @Utkarsh-Deshmukh, 

I was trying to run your code on fingerprint patches resized to 256x256. The ridges maps aren't formed completely(might be due to pores). There is also a black border along the edges but I need the ridge map for the complete image. 

I have attached the resulting ridge map below along with the original image. Could you please guide me on resolving these issues?

Original Image (96x96)
![1801-019_0_1-HiScan-Live](https://user-images.githubusercontent.com/32260835/126077257-4d9de801-d5f9-4223-84ca-a966d4267b98.png)

Enhanced Ridge Map Image (256x256)
![enhanced_image1801-019_0_1-HiScan-Live](https://user-images.githubusercontent.com/32260835/126077352-146fbe69-b8bf-4d04-9831-7a063cec6d19.png)

Thank you

**Comment by Utkarsh-Deshmukh** [comment]
This must be be happening due to mismatch of window size for the input image that you are providing. I have seen this behavior before. If you can provide me with the original image, i can fix it and let you know what parameters work best for your use case. Thank you

**Comment by Utkarsh-Deshmukh** [comment]
I see what is happening. By resizing it to 256x256, you are making the pores really huge (avoid such a large resizing). I resized the image to 128x128 and the results look very nice. Here is what my result looks like:
![image](https://user-images.githubusercontent.com/13918778/126108281-8b658596-c2a2-497c-a6bf-28380b82a4c5.png)

Here is the code snippet that generated this result:
![image](https://user-images.githubusercontent.com/13918778/126108467-82b1f88c-d544-4ab5-a72d-dc928b692bba.png)



By resizing the image to such a large value, all the internal filters need to be resized. Easier solution is to avoid such a large resize operation.

**Comment by gowrijsuria** [comment]
Thanks a lot! Is there any way to remove the extra black border on the side? For my final use case, I need to take L1 loss on the perfect ridge maps, but some content is lost at the edges.

**Comment by Utkarsh-Deshmukh** [comment]
The reason some content is lost at the borders in order to run the filters on the original image, we neglect the regions on the border. The easiest thing you can do is to artificially add border to your input image, enhance it and then remove the border from the output.
