### ISSUE TITLE
Slight different in Cos image.

### ISSUE THREAD

**Issue by michealChin** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#16]
Hi,

I have converted the code to pure c# however there are some discrepancy on the final image. So I try to visualize the orientation image for Sin, Cos and etc

I found out the Cos image generated from c# is as follow
![cos](https://user-images.githubusercontent.com/12890191/155304750-45cd3e01-23ba-41fb-8914-ff3e889936de.jpg)
Generated by Python code
![cos](https://user-images.githubusercontent.com/12890191/155304854-bef70fcc-419e-4bc4-af2d-6aaa31f0f80c.jpg)

Orientation (c#)
![orientation](https://user-images.githubusercontent.com/12890191/155306351-28b0358d-8d35-421f-a873-1deb7f6b693f.jpg)
Orientation (Python)
![1](https://user-images.githubusercontent.com/12890191/155306365-e3e1e724-f3c0-4271-a824-750286a06a97.jpg)

Here is the original fingerprint
![1](https://user-images.githubusercontent.com/12890191/155305131-ae443845-ba51-4ebe-8140-91cc8b149b1b.jpg)

Enhance result from c# 

![testout](https://user-images.githubusercontent.com/12890191/155305547-4cd04488-d3d5-454d-a83d-f5594c88eeca.jpg)

Enhance result from Python

![1](https://user-images.githubusercontent.com/12890191/155305609-8ebccdd6-a2e0-4c94-abb6-8fe8ac8e1869.jpg)

Could it be the different in the Cos orientation image as generated by both C# and Python that cause the subsequence failure in the final enhance image?

**Comment by Utkarsh-Deshmukh** [comment]
here are a few points that you can debug on:
- if the `sin` image is similar but the `cos` image is different, that is an issue. can you figure out what that would be happening?
- can you verify the gabor filter bank that you generate is correct or not?
- In the python code, there would be a variable in the function `__ridge_freq` called `_mean_freq`. Can you verify if this value matches with the one which you have derived?

**Comment by michealChin** [comment]
Finally I got my C# version working! Thanks again for you kind sharing! Hope you have a nice day!
![testout](https://user-images.githubusercontent.com/12890191/155478536-5a0511a4-75f8-4793-aada-6cc53a976dec.jpg)

**Comment by Utkarsh-Deshmukh** [comment]
glad that it worked!
