### ISSUE TITLE
Discrepancy between the enhance images generated from python and c# code

### ISSUE THREAD

**Issue by michealChin** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#17]
Here is the result generated from 
C#
![testout](https://user-images.githubusercontent.com/12890191/155815590-7d6b6ebb-d9ba-49a3-b175-ff4f81dcec3c.jpg)

Python 
![Untitled](https://user-images.githubusercontent.com/12890191/155815719-80c44642-81ad-43b9-8ef2-047691f62764.png)

The ridges generated from original image are more thicker and connected while the one using openCV replacement function are thinner and disconnected.

There are a lot of useful library found in python but didn't provided by C# so I have to make some changes on certain function call, mainly using opencv to replace sciPy's function.

In the ridge_orient() function
I replace 
```
        gauss = cv2.getGaussianKernel(np.int(sze),self.gradient_sigma)
        f = gauss * gauss.T

        fy,fx = np.gradient(f)    

        Gx = signal.convolve2d(self._normim, fx, mode='same')
        Gy = signal.convolve2d(self._normim, fy, mode='same')

        Gxx = ndimage.convolve(Gxx,f)
        Gyy = ndimage.convolve(Gyy,f)
        Gxy = 2*ndimage.convolve(Gxy,f)
```
with
```
        gauss = cv2.getGaussianKernel(np.int(sze),self.gradient_sigma)
        f = gauss * gauss.T

        fx=cv2.Sobel(f,cv2.CV_64F,1,0,3)
        fy=cv2.Sobel(f,cv2.CV_64F,0,1,3)

       Gx = cv2.filter2D(self._normim,-1,cv2.flip(fx,-1),borderType=cv2.BORDER_REFLECT)
        Gy = cv2.filter2D(self._normim,-1,cv2.flip(fy,-1),borderType=cv2.BORDER_REFLECT)

        Gxx = cv2.filter2D(Gxx,-1,cv2.flip(f,-1),borderType=cv2.BORDER_REFLECT)
        Gyy = cv2.filter2D(Gyy,-1,cv2.flip(f,-1),borderType=cv2.BORDER_REFLECT)
        Gxy = 2*cv2.filter2D(Gxy,-1,cv2.flip(f,-1),borderType=cv2.BORDER_REFLECT)

```
__frequest()

I replace 
```
rotim = scipy.ndimage.rotate(blkim, orient / np.pi * 180 + 90, axes=(1, 0), reshape=False, order=3,
                                    mode='nearest')
```
with

```
       ROT_mat = cv2.getRotationMatrix2D((cols/2,rows/2),orient/np.pi*180 + 90,1)
        rotim = cv2.warpAffine(blkim,ROT_mat,(cols,rows))
```

What is the reason that cause such discrepancy? Any Idea to make the ridge thicker and connected? Thanks in advance

**Comment by michealChin** [comment]
I found the reason already.

**Comment by skyestudiosDev** [comment]
@michealChin did you open source your implementation? looking at writing a java port.

**Comment by Utkarsh-Deshmukh** [comment]
@michealChin what was the fix? it would be good to mention it here, so that others find it useful in the future

**Comment by michealChin** [comment]
> @michealChin did you open source your implementation? looking at writing a java port.

Sorry I didn't open source my project.

**Comment by michealChin** [comment]
> @michealChin what was the fix? it would be good to mention it here, so that others find it useful in the future

Recently I am a bit busy, maybe will update when I am free.
