### ISSUE TITLE
How to run this code? which IDE?

### ISSUE THREAD

**Issue by Chabubakar314** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#18]
I want to run this project but failed many times

**Comment by Utkarsh-Deshmukh** [comment]
you can run this library by installing it from pip. check out the readme file in this project.
If you have any errors, please post them so that I can understand what exactly is going wrong..
Best Regards

**Comment by cool4120** [comment]
i was running this file in jupyter notebook and its showing this error No module named 'src'

**Comment by Utkarsh-Deshmukh** [comment]
can you try and run it locally? Try with VSCode or Pycharm or just regular terminal
