### ISSUE TITLE
TypeError showing

### ISSUE THREAD

**Issue by richk21** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#21]
Hi!
I was just trying to run this code. I got an error that there's no attribute "int" for module numPy. I converted that to normal int() function. Now I'm getting a new error "TypeError: only size-1 arrays can be converted to Python scalars" on the line "cropsze = int(np.fix(rows // np.sqrt(2)))". Can you tell me what I'm doing wrong? Should i change my python version or opencv version?

**Comment by Utkarsh-Deshmukh** [comment]
@richk21 can you please send me the image on which you are trying to run this, so that I can try to recreate this error on my end?

**Comment by Utkarsh-Deshmukh** [comment]
closing the issue due to inactivity for 5 months
