### ISSUE TITLE
Program behaves weird

### ISSUE THREAD

**Issue by KoujiHeneda** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#25]
I tried to input an image, but the image is kind of buggy. In the original image, there are some white lines in the centre of the fingerprint. This feature feels as if there is some glitch when it comes to enhancing the picture. The input image is in the bmp format.
This is the input image:
![input](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/ceff4d77-5c33-4583-b45d-9221f8310d6e)
And this is the output image:
![enhanced](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/473e19ac-7136-493d-87c9-e7c6eeaf5e6f)

**Comment by Utkarsh-Deshmukh** [comment]
@KoujiHeneda unfortunately, these presence of really strong scars are hard to overcome. the original script is not capable of handling this. As a hack around, you can modify the `__ridge_filter` function in the fingerprint_enhancer library and add the following code in the line which says `newim[r][c] = np.sum(img_block * gabor_filter[int(orientindex[r][c]) - 1])`
```

            if np.mean(img_block) >50:
                newim[r][c] = 0
            else:
                newim[r][c] = np.sum(img_block * gabor_filter[int(orientindex[r][c]) - 1])

```

By doing this, you are essentially saying that only perform the filtering if the underlying area appears to be dark (that means if and only if the underlying area is a part of a ridge)

By doing this I get an output like this:
![image](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/13918778/254d0a56-6788-4cc5-aef7-2d05e51e78b0)

There isnt too much improvement.

**Comment by KoujiHeneda** [comment]
Thanks

**Comment by KoujiHeneda** [comment]
Also, is there any way to overcome such issues?
