### ISSUE TITLE
More problems

### ISSUE THREAD

**Issue by KoujiHeneda** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#26]
I tried converting some more images, and some images still behave buggy. I know it is very hard to solve, but are there any approaches to solve it? Also, I found out the later version of the code still somehow can't work as intended and even makes it worse.
Original:
![6](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/06615b9c-6e2d-4953-aaeb-be6f929eebed)
pip:
![6 (2)](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/4deac5e9-2bde-4c37-a5ac-da6fcbe07989)
Raw code:
![6 (1)](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/9d52ce8c-5e65-4c9e-abda-6d11e19b8efb)

**Comment by Utkarsh-Deshmukh** [comment]
try playing around with the parameters.

**Comment by KoujiHeneda** [comment]
Which parameter(s) do I need to play with?

**Comment by KoujiHeneda** [comment]
It is pretty weird to me that the pip version is a bit different than the actual code version.

**Comment by KoujiHeneda** [comment]
And I checked the pip version as well as the actual code version, the parameters I believed are the same(default)

**Comment by Utkarsh-Deshmukh** [comment]
there are some tunable parameters whose default values might be different in the pip version vs the source codes.
Here is a list of all the arguments that might need some tweaking:
```
self.ridge_segment_blksze = 16
self.ridge_segment_thresh = 0.1
self.gradient_sigma = 1
self.block_sigma = 7
self.orient_smooth_sigma = 7
self.ridge_freq_blksze = 38
self.ridge_freq_windsze = 5
self.min_wave_length = 5
self.max_wave_length = 15
self.relative_scale_factor_x = 0.65
self.relative_scale_factor_y = 0.65
self.angle_inc = 3
self.ridge_filter_thresh = -3
```

**Comment by KoujiHeneda** [comment]
From my perspective, the pip version as well as the raw code version have the same parameters, yet their results are completely different.
pip: 
![捕获](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/46c52b3b-efd6-45e1-bfbe-d27d6bbe8bf1)
raw code:
![image](https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/assets/74016231/2b3c3031-07ca-4724-a765-0f3dc714a544)

**Comment by Utkarsh-Deshmukh** [comment]
there was a bug introduced in the previous merge.. I have fixed it now.. now the outputs should be the same.
Thank you for pointing it out

**Comment by KoujiHeneda** [comment]
I have no idea, from my perspective, the output are still different

**Comment by Utkarsh-Deshmukh** [comment]
can you verify if you are **not** resizing the images for both the cases?

**Comment by KoujiHeneda** [comment]
They are finally the same, I didn't realize that the resize is set to True by default, and by the way, is it possible to fix the problem for the scar part in the future?

**Comment by Utkarsh-Deshmukh** [comment]
the scar appears to be a really strong artifact.. I dont think this approach might be capable to fix it.. it is meant for fixing minor scars.

**Comment by KoujiHeneda** [comment]
Thank you.
