### ISSUE TITLE
some problem about ridge_orient 

### ISSUE THREAD

**Issue by Lemanz** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#3]
Hi, Utkarsh
When I saw the code "orientim = np.pi/2 + np.arctan2(sin2theta,cos2theta)/2;" in ridge_orient.py,
I was confused about why need to add pi/2. Then, I drew a directional field on a img,but it looked irregular.
Looking forward  to your reply.

**Comment by Utkarsh-Deshmukh** [comment]
> Hi, Utkarsh
> When I saw the code "orientim = np.pi/2 + np.arctan2(sin2theta,cos2theta)/2;" in ridge_orient.py,
> I was confused about why need to add pi/2. Then, I drew a directional field on a img,but it looked irregular.
> Looking forward to your reply.

Could you send me the image on which you are testing this. also could you upload a snapshot of the direction field. This will help me recreate the problem on  my end.

**Comment by Utkarsh-Deshmukh** [comment]
Sorry. I forgot to answer your question. I believe the pi/2 is added to convert from geometric coordinates to image pixel coordinates.

**Comment by Lemanz** [comment]
> > Hi, Utkarsh
> > When I saw the code "orientim = np.pi/2 + np.arctan2(sin2theta,cos2theta)/2;" in ridge_orient.py,
> > I was confused about why need to add pi/2. Then, I drew a directional field on a img,but it looked irregular.
> > Looking forward to your reply.
> 
> Could you send me the image on which you are testing this. also could you upload a snapshot of the direction field. This will help me recreate the problem on my end.

**Comment by Lemanz** [comment]
Thanks for your reply.
I understand the ridge orient because of your help.
Now, directional field is ok. Thank you again for sharing the code.







------------------ 原始邮件 ------------------
发件人: "Utkarsh Deshmukh"<notifications@github.com>;
发送时间: 2019年9月7日(星期六) 凌晨2:54
收件人: "Utkarsh-Deshmukh/Fingerprint-Enhancement-Python"<Fingerprint-Enhancement-Python@noreply.github.com>;
抄送: "胜利"<574531903@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python] some problemabout ridge_orient  (#3)




Sorry. I forgot to answer your question. I believe the pi/2 is added to convert from geometric coordinates to image pixel coordinates.
