### ISSUE TITLE
Problem about running

### ISSUE THREAD

**Issue by SerhiiDmytruk** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#4]
Hi there!
I'm trying to run this project, but there are some errors. I have tried to fix them but anyway can't run. I attach the 1st screenshot of the first error. This error I've fixed placing '//' instead of '/'. Then was similar error and after was error like on 2nd screenshot.
I'm on windows 10 and using Anaconda 2 spyder (Python 3.7)
![image](https://user-images.githubusercontent.com/42764709/66516699-5624a600-eaea-11e9-950a-8477ded76064.png)
![image](https://user-images.githubusercontent.com/42764709/66517064-15795c80-eaeb-11e9-9a23-87c363ce9a22.png)

**Comment by Utkarsh-Deshmukh** [comment]
Could you check what is the version of your scipy module? the one which I used was 1.2.2
Could you change your scipy version to 1.2.2 and check if you still get this error?

**Comment by SerhiiDmytruk** [comment]
I couldn't change to 1.2.2 but now i have 1.3.1
And now i have another error:
![image](https://user-images.githubusercontent.com/42764709/66561061-63c94280-eb61-11e9-9277-8a4f1950e6a3.png)

**Comment by Utkarsh-Deshmukh** [comment]
I have created a branch called "ImageReadUsingOpencv" which uses opencv instead of scipy to handle the image reading and writing stuff.

Here are the versions of libraries that I have tested with:
numpy --> 1.17.2
opencv-python  --> 4.1.1.26
scipy --> 1.3.1

Here is the link to the branch:
https://github.com/Utkarsh-Deshmukh/Fingerprint-Enhancement-Python/tree/ImageReadUsingOpencv

Let me know if this works.

**Comment by SerhiiDmytruk** [comment]
Thank you! Now it works.
But if i delete enhanced images it shows such message
![image](https://user-images.githubusercontent.com/42764709/66834504-6b745700-ef66-11e9-9a79-55aa5f282583.png)
And returns 1st picture only

**Comment by Utkarsh-Deshmukh** [comment]
That is how it is programmed to work. If you open the file main_enhancement.py, you will see that the default image it reads is the '1.jpg'

you will have to modify this file to enhance your sample image.
