### ISSUE TITLE
Execute problem 

### ISSUE THREAD

**Issue by laylatheraven** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#5]
Hello Utkarsh, maybe the problem is so silly and the solution is so simple but i'cant execute main_enhancement.py in anaconda. The error is: AttributeError: module 'scipy.ndimage' has no attribute 'imread'. I try to change the ndimage to misc and imageio but it doesn't help, error is the same. While i've been search for the solution (especially on stackoverflow) i saw that someone else's problem solved with importing pillow, so i tried it too but nothing changed. Is this problem occurs because of the version differences? What do you think?

**Comment by Utkarsh-Deshmukh** [comment]
can you confirm what version are you using for the following libraries:
- Pillow
- scipy

**Comment by Utkarsh-Deshmukh** [comment]
I have seen scipy giving some trouble. In order to not depend on it, I am using opencv to perform the image reading and writing. I just merged this change into the latest commit. You can get the working code from the top of the commit list.

Let me know if this works

**Comment by laylatheraven** [comment]
Versions are:
Pillow-6.2.1
scipy-1.3.3

Thanks for answering so quickly, i'll try it and let you know the result as soon as possible.

**Comment by laylatheraven** [comment]
It worked, thank you very much :)
