### ISSUE TITLE
Issue with ridge_filter

### ISSUE THREAD

**Issue by Downlosc** [Utkarsh-Deshmukh/Fingerprint-Enhancement-Python#7]
Hi, I am using this library on my fingerprint dataset and i get this error:

`in ridge_filter(im, orient, freq, kx, ky)
     75     # orientations in 'angleInc' increments.
     76 
---> 77     sigmax = 1/unfreq[0]*kx;
     78     sigmay = 1/unfreq[0]*ky;
     79 

IndexError: index 0 is out of bounds for axis 0 with size 0`

Can you help me?

**Comment by Downlosc** [comment]
It works on the first image on the dataset but it stops on the second image giving that error. 
All the images have the same shape and i am doublechecking that they are not None.

**Comment by Utkarsh-Deshmukh** [comment]
Can you send me the image which produced this error for you?

**Comment by Utkarsh-Deshmukh** [comment]
> Hi, I am using this library on my fingerprint dataset and i get this error:
> 
> `in ridge_filter(im, orient, freq, kx, ky)
> 75 # orientations in 'angleInc' increments.
> 76
> ---> 77 sigmax = 1/unfreq[0]*kx;
> 78 sigmay = 1/unfreq[0]*ky;
> 79
> 
> IndexError: index 0 is out of bounds for axis 0 with size 0`
> 
> Can you help me?

were you able to fix this?
